name: deploy
on:
  push:
    branches: ['main']
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund --prefer-offline

      - name: Run lint checks
        run: npm run lint || echo "Lint warnings found, but continuing..."

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=new-asap-side \
            -Dsonar.projectKey=new-asap-side_asap-backend \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts \
            -Dsonar.tests=src \
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts \
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io
            
  deploy:
    runs-on: ubuntu-latest
    needs: sonarcloud
    environment:
      name: production  # 환경 이름을 지정
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t tslee1996y/asap-back:latest .
          docker push tslee1996y/asap-back:latest

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_SERVER_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            docker image prune -f || true
            docker pull tslee1996y/asap-back:latest
            
            # 기존 서비스를 제거
            docker service rm asapserver || true
                    
            # 새로운 Docker Swarm 서비스 생성
            docker service create \
            --name asapserver \
            --publish 80:3000 \
            --publish 443:3000 \
            --env NODE_ENV=${{ secrets.NODE_ENV }} \
            --env DB_HOST=${{ secrets.DB_HOST }} \
            --env DB_PORT=${{ secrets.DB_PORT }} \
            --env DB_PW=${{ secrets.DB_PW }} \
            --env DB_USER=${{ secrets.DB_USER }} \
            --env DB_DATABASE=${{ secrets.DB_DATABASE }} \
            --env KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }} \
            --env CODE_REDIRECT_URI=${{ secrets.CODE_REDIRECT_URI }} \
            --env JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            --env JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }} \
            --env JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }} \
            --env JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }} \
            --env FIRE_BASE_CONFIG=${{ secrets.FIRE_BASE_CONFIG }} \
            --env REDIS_HOST=${{ secrets.REDIS_HOST }} \
            --env REDIS_PORT=6379 \
            --env URL_BASE_PATH=${{ secrets.URL_BASE_PATH }} \
            --env S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} \
            --env S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} \
            --env APNS_P8_FILE_STRING=${{ secrets.APNS_P8_FILE_STRING }} \
            --env APNS_KEY_ID=${{ secrets.APNS_KEY_ID }} \
            --env APNS_TEAM_ID=${{ secrets.APNS_TEAM_ID }} \
            --env APNS_PRODUCTION=${{ secrets.APNS_PRODUCTION }} \
            --env APNS_BUNDLE_ID=${{ secrets.APNS_BUNDLE_ID }} \
            tslee1996y/asap-back:latest
